### ISSUE TITLE
Cannot replicate post

### ISSUE THREAD

**Issue by nunocalaim** [distillpub/post--selforg-mnist#8]
I downloaded post--selforg-mnist, unzipped it, opened public/index.html expecting to be able to use the demo

but nothing interactive is working there. The demo is simply blank and no buttons react. The entire post is there but no video play, etc.

Is this a problem of my machine? Is this a bug? or the github repo was never expected to be interactive?

**Comment by nunocalaim** [comment]
Oh forgot to say! Very cool work! I loved it

**Comment by eyvindn** [comment]
This repository hosts the files for the distill article itself. 

If you want to replicate the work itself, including a tf.js demo, please press ["Try in Colab"](https://colab.research.google.com/github/google-research/self-organising-systems/blob/master/notebooks/mnist_ca.ipynb) in the article. 

However, if you really want to have a locally hosted version of the article, then download this repository and host it using the simple python webserver included. To get a live version of the site, run this comman\

> python bin/dev.py

And navigate to [http://localhost:8000/](http://localhost:8000/). This repository is based on our simple google docs -> distill draft script, available [here](https://github.com/znah/gdocs_distill_template), where you can also find more information.

**Comment by nunocalaim** [comment]
Thank you for your reply.

I had tried it on the google collab and it is not working for me in firefox, but now I tried Chrome and it works (might be something about my firefox)

yes, I would like to have a locally hosted version of the article for me to play around with interactive visualisation in the browser and tensorflowjs.
I am confused though why the need for a webserver.. I thought that pure javascript (which is what I think what tensorflowjs is there for) works without a server behind it. Could you clarify this point? In other words, why is the demo part not exclusively javascript and needs to somehow be calling python? or am I missing something?

**Comment by eyvindn** [comment]
It's possible there's tf.js issues in Firefox. Would you mind sharing the Firefox version and platform, or the error you encountered? 

The demo is exclusively JS, yes. We host a local server for a few reasons, such as having a staging version of the article for all authors and reviewers to view, and to replicate the hosting environment once the article goes live on distill.pub. 

If you want a standalone version of demo, I would recommend viewing `demo.html` and modifying it so the dependencies it tries to load are in the right place, and it should work standalone by just opening the .html in a browser. Let me know if you run into any issues.
